[build]
target = ["x86_64-pc-windows-msvc","wasm32-unknown-unknown"]
# target = ["x86_64-apple-darwin", "aarch64-apple-darwin", "wasm32-unknown-unknown"]
# target = ["x86_64-apple-darwin"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg=web_sys_unstable_apis']

[alias]
run-wasm = ["run", "--release", "--package", "run-wasm", "--"]
