[workspace]
resolver = "2"
members = [
    "app",
    "run-wasm",
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
cfg-if = "1"
derivative = "2.2"
glam = "0.21"